version: '3.2'

services:
  agent:
    image: dynamiteai/nsm-1.2
    environment:
      - ENABLE_ZEEK=true
      - ENABLE_SURICATA=true
      - TARGETS=https://localhost:9200
    build: .
    cap_add:
      - net_raw
      - net_admin
    network_mode: host
    volumes:
      - type: bind
        source: ./logs/suricata
        target: /opt/dynamite/suricata/logs


