name: Logstash Installer
on: [pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v1
    - name: Install DynamiteNSM
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install .
    - name: Setup DynamiteNSM
      run: |
        sudo dynamite setup install
    - name: Install Logstash
      run: |
        sudo dynamite logstash install --verbose
    - name: Run Post-Install Tests
      run: |
        echo Skipping for now.
    - name: Start Logstash Processes
      run: |
        sudo dynamite logstash process start
    - name: Stop Logstash Processes
      run: |
        sudo dynamite logstash process stop
