import os
ELASTICSEARCH_ARCHIVE_NAME = 'elasticsearch-7.1.1.tar.gz'
LOGSTASH_ARCHIVE_NAME = 'logstash-7.1.1.tar.gz'
JAVA_ARCHIVE_NAME = 'java-11.0.2.tar.gz'
INSTALL_CACHE = os.environ['DYNAMITE_INSTALL_CACHE']
DEFAULT_CONFIGS = os.environ['DEFAULT_CONFIGS']
ELASTICSEARCH_MIRRORS = os.environ['ELASTICSEARCH_LINUX_MIRRORS']
LOGSTASH_MIRRORS = os.environ['LOGSTASH_LINUX_MIRRORS']
JAVA_MIRRORS = os.environ['JAVA_LINUX_MIRRORS']